import {CamionModel} from "./camion.model";
import {DeclarationFretModel} from "./declaration-fret.model";
import {ParametrageModel} from "./parametrage.model";

export interface AffretementModel {
  id: number;
  conducteur: number;
  camion: number;
  camionObj: CamionModel;
  nomCamion: string;
  poidsAffecte: number;
  poids: number;
}


export interface CreateAffretementModel {
  declarationFret: number;
  camions: AffretementModel[];
}

export interface CreateAffretementAllModel {
  declarationFret: number;
  affretements: OmitAffretementModel[];
}

export interface OmitAffretementModel {
  parametrage: number;
  quota?: number;
  poidsAffecte?: number;
  camions: Omit<AffretementModel, 'id' & 'conducteur' & 'poidsAffecte'>[];
}


const data = {
  "data": [
    {
      "id": 96,
      "declarationFret": {
        "id": 104,
        "declarant": {
          "id": 21,
          "maisonTransit": "GLORIA",
          "telephone": "91298899",
          "mail": "aggloria@gmail.com",
          "compteClient": "C464600",
          "createdBy": "Gloria Gloria",
          "createdAt": 1734371818356,
          "updateBy": null,
          "updateAt": 1734371818356
        },
        "chargeur": {
          "id": 27,
          "nom": "Conseil des chargeurs CBC",
          "nationalite": "Burkinabé",
          "telephone": "91298899",
          "mail": "acbc@gmail.com",
          "repartitionFret": true,
          "compteClient": "C407000",
          "quotas": 0.6,
          "createdBy": "Conseil des chargeurs CBC",
          "createdAt": 1734373877310,
          "updateBy": null,
          "updateAt": 1734373877310
        },
        "destinataireMarchandise": {
          "id": 63,
          "nom": "BARRO'S",
          "email": "info@barros.com",
          "telephone": "+226 70 27 97 53",
          "nationalite": "Burkinabé",
          "createdBy": "Gloria Gloria",
          "createdAt": 1734371818366,
          "updateBy": null,
          "updateAt": 1734371818366
        },
        "pieceJustificatives": null,
        "codeSh": "234",
        "natureMarchandise": "BLE",
        "produitGrandeConsommation": true,
        "sensTrafic": "IMP",
        "modeTransport": "Route",
        "origineMarchandise": "CHINE",
        "blNumeroConnaissement": "0009238881",
        "portEmbarquement": "PAL",
        "nomNavire": "NAVI-TRANS",
        "nationaliteNavire": "CHINOISE",
        "nombreCamionsSouhaite": 6,
        "prixTransportSouhaiteTonne": 35000,
        "affichagePrixRecepisse": true,
        "paysProvenance": "CHINE",
        "poidsMarchandise": 3000,
        "villeProvenance": "HONG KONG",
        "paysDestination": "BURKINA FASO",
        "villeDestination": "Ouagadougou",
        "createdBy": "C464600",
        "statutPayement": null,
        "statutAffretement": true,
        "etatMarchandise": "TRANSIT",
        "datePayement": null,
        "createdAt": 1736860911573,
        "updateBy": null,
        "updateAt": 1736861304096
      },
      "affretementCamions": [
        {
          "id": 5,
          "camion": {
            "id": 87,
            "transporteur": {
              "id": 45,
              "raisonSociale": "Marco Transporteur",
              "telephone": "91131955",
              "adresse": null,
              "mail": "transporteur013@gmail.com",
              "nif": null,
              "rccm": null,
              "licenceTransport": null,
              "createdBy": "Marco Transporteur",
              "createdAt": 1736181596124,
              "updateBy": null,
              "updateAt": 1736181596124
            },
            "conducteur": {
              "id": 24,
              "nom": "Campaoré",
              "prenoms": "Moussa",
              "numeroTelephone": "90 62 44 11",
              "numeroPermis": "960-80-45700",
              "dateEtablissementPermis": 1266087840000,
              "lieuEtablissementPermis": "Ouagadougou",
              "associationAffiliation": "URT",
              "dateExpPermis": 1736441698000,
              "nationalite": "CNI-82-123-0050",
              "dateNaissance": "1980-02-26T19:04",
              "genre": "homme",
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734375909750,
              "updateBy": null,
              "updateAt": 1734375909750
            },
            "immatriculation": "BF-94059",
            "chargeUtile": 400,
            "capaciteAutorisee14": 400,
            "nombreEssieu": 6,
            "dateExpVisiteTechnique": 1739059200000,
            "dateExpAssurance": 1739059200000,
            "pays": "BURKINA FASO",
            "nationalite": "Burkinabé",
            "marque": "MAN",
            "modeleCarteGrise": "Poids Lourd",
            "numeroCarteGrise": "07688832",
            "numeroCarteTransport": "CT-087592",
            "disponible": true,
            "piecesJustificatives": null,
            "etatCamion": "VALIDER",
            "motifRejete": null,
            "createdBy": "Marco Transporteur",
            "createdAt": 1736512177811,
            "updateBy": null,
            "updateAt": 1736513514018
          },
          "affretement": {
            "id": 96,
            "declarationFret": {
              "id": 104,
              "declarant": {
                "id": 21,
                "maisonTransit": "GLORIA",
                "telephone": "91298899",
                "mail": "aggloria@gmail.com",
                "compteClient": "C464600",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818356,
                "updateBy": null,
                "updateAt": 1734371818356
              },
              "chargeur": {
                "id": 27,
                "nom": "Conseil des chargeurs CBC",
                "nationalite": "Burkinabé",
                "telephone": "91298899",
                "mail": "acbc@gmail.com",
                "repartitionFret": true,
                "compteClient": "C407000",
                "quotas": 0.6,
                "createdBy": "Conseil des chargeurs CBC",
                "createdAt": 1734373877310,
                "updateBy": null,
                "updateAt": 1734373877310
              },
              "destinataireMarchandise": {
                "id": 63,
                "nom": "BARRO'S",
                "email": "info@barros.com",
                "telephone": "+226 70 27 97 53",
                "nationalite": "Burkinabé",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818366,
                "updateBy": null,
                "updateAt": 1734371818366
              },
              "pieceJustificatives": null,
              "codeSh": "234",
              "natureMarchandise": "BLE",
              "produitGrandeConsommation": true,
              "sensTrafic": "IMP",
              "modeTransport": "Route",
              "origineMarchandise": "CHINE",
              "blNumeroConnaissement": "0009238881",
              "portEmbarquement": "PAL",
              "nomNavire": "NAVI-TRANS",
              "nationaliteNavire": "CHINOISE",
              "nombreCamionsSouhaite": 6,
              "prixTransportSouhaiteTonne": 35000,
              "affichagePrixRecepisse": true,
              "paysProvenance": "CHINE",
              "poidsMarchandise": 3000,
              "villeProvenance": "HONG KONG",
              "paysDestination": "BURKINA FASO",
              "villeDestination": "Ouagadougou",
              "createdBy": "C464600",
              "statutPayement": null,
              "statutAffretement": true,
              "etatMarchandise": "TRANSIT",
              "datePayement": null,
              "createdAt": 1736860911573,
              "updateBy": null,
              "updateAt": 1736861304096
            },
            "affretementCamions": null,
            "createdBy": "chargeur Client",
            "createdAt": 1736861304007,
            "updateBy": null,
            "updateAt": 1736861304007
          },
          "parametrage": {
            "id": 14,
            "chargeur": {
              "id": 27,
              "nom": "Conseil des chargeurs CBC",
              "nationalite": "Burkinabé",
              "telephone": "91298899",
              "mail": "acbc@gmail.com",
              "repartitionFret": true,
              "compteClient": "C407000",
              "quotas": 0.6,
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734373877310,
              "updateBy": null,
              "updateAt": 1734373877310
            },
            "nationalite": "Burkinabé",
            "quota": 0.6,
            "type": "TRANSIT",
            "createdBy": "Conseil des chargeurs CBC",
            "updateBy": null,
            "createdAt": 1736776199272,
            "updateAt": 1736776199272
          },
          "poids": 400
        },
        {
          "id": 6,
          "camion": {
            "id": 88,
            "transporteur": {
              "id": 45,
              "raisonSociale": "Marco Transporteur",
              "telephone": "91131955",
              "adresse": null,
              "mail": "transporteur013@gmail.com",
              "nif": null,
              "rccm": null,
              "licenceTransport": null,
              "createdBy": "Marco Transporteur",
              "createdAt": 1736181596124,
              "updateBy": null,
              "updateAt": 1736181596124
            },
            "conducteur": {
              "id": 23,
              "nom": "Ouedraogo",
              "prenoms": "troaré",
              "numeroTelephone": "92 32 45 55",
              "numeroPermis": "550-20-45300",
              "dateEtablissementPermis": 950814060000,
              "lieuEtablissementPermis": "Ouagadougou",
              "associationAffiliation": "URT",
              "dateExpPermis": 1736441708000,
              "nationalite": "CNI-70-123-0030",
              "dateNaissance": "1980-01-17T19:00",
              "genre": "homme",
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734375753622,
              "updateBy": null,
              "updateAt": 1734375753622
            },
            "immatriculation": "BF-9810",
            "chargeUtile": 600,
            "capaciteAutorisee14": 600,
            "nombreEssieu": 6,
            "dateExpVisiteTechnique": 1739059200000,
            "dateExpAssurance": 1739059200000,
            "pays": "BURKINA FASO",
            "nationalite": "Burkinabé",
            "marque": "MAN",
            "modeleCarteGrise": "Poids Lourd",
            "numeroCarteGrise": "099281",
            "numeroCarteTransport": "CT-09943",
            "disponible": true,
            "piecesJustificatives": null,
            "etatCamion": "VALIDER",
            "motifRejete": null,
            "createdBy": "Marco Transporteur",
            "createdAt": 1736512414515,
            "updateBy": null,
            "updateAt": 1736513411318
          },
          "affretement": {
            "id": 96,
            "declarationFret": {
              "id": 104,
              "declarant": {
                "id": 21,
                "maisonTransit": "GLORIA",
                "telephone": "91298899",
                "mail": "aggloria@gmail.com",
                "compteClient": "C464600",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818356,
                "updateBy": null,
                "updateAt": 1734371818356
              },
              "chargeur": {
                "id": 27,
                "nom": "Conseil des chargeurs CBC",
                "nationalite": "Burkinabé",
                "telephone": "91298899",
                "mail": "acbc@gmail.com",
                "repartitionFret": true,
                "compteClient": "C407000",
                "quotas": 0.6,
                "createdBy": "Conseil des chargeurs CBC",
                "createdAt": 1734373877310,
                "updateBy": null,
                "updateAt": 1734373877310
              },
              "destinataireMarchandise": {
                "id": 63,
                "nom": "BARRO'S",
                "email": "info@barros.com",
                "telephone": "+226 70 27 97 53",
                "nationalite": "Burkinabé",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818366,
                "updateBy": null,
                "updateAt": 1734371818366
              },
              "pieceJustificatives": null,
              "codeSh": "234",
              "natureMarchandise": "BLE",
              "produitGrandeConsommation": true,
              "sensTrafic": "IMP",
              "modeTransport": "Route",
              "origineMarchandise": "CHINE",
              "blNumeroConnaissement": "0009238881",
              "portEmbarquement": "PAL",
              "nomNavire": "NAVI-TRANS",
              "nationaliteNavire": "CHINOISE",
              "nombreCamionsSouhaite": 6,
              "prixTransportSouhaiteTonne": 35000,
              "affichagePrixRecepisse": true,
              "paysProvenance": "CHINE",
              "poidsMarchandise": 3000,
              "villeProvenance": "HONG KONG",
              "paysDestination": "BURKINA FASO",
              "villeDestination": "Ouagadougou",
              "createdBy": "C464600",
              "statutPayement": null,
              "statutAffretement": true,
              "etatMarchandise": "TRANSIT",
              "datePayement": null,
              "createdAt": 1736860911573,
              "updateBy": null,
              "updateAt": 1736861304096
            },
            "affretementCamions": null,
            "createdBy": "chargeur Client",
            "createdAt": 1736861304007,
            "updateBy": null,
            "updateAt": 1736861304007
          },
          "parametrage": {
            "id": 14,
            "chargeur": {
              "id": 27,
              "nom": "Conseil des chargeurs CBC",
              "nationalite": "Burkinabé",
              "telephone": "91298899",
              "mail": "acbc@gmail.com",
              "repartitionFret": true,
              "compteClient": "C407000",
              "quotas": 0.6,
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734373877310,
              "updateBy": null,
              "updateAt": 1734373877310
            },
            "nationalite": "Burkinabé",
            "quota": 0.6,
            "type": "TRANSIT",
            "createdBy": "Conseil des chargeurs CBC",
            "updateBy": null,
            "createdAt": 1736776199272,
            "updateAt": 1736776199272
          },
          "poids": 600
        },
        {
          "id": 7,
          "camion": {
            "id": 103,
            "transporteur": {
              "id": 45,
              "raisonSociale": "Marco Transporteur",
              "telephone": "91131955",
              "adresse": null,
              "mail": "transporteur013@gmail.com",
              "nif": null,
              "rccm": null,
              "licenceTransport": null,
              "createdBy": "Marco Transporteur",
              "createdAt": 1736181596124,
              "updateBy": null,
              "updateAt": 1736181596124
            },
            "conducteur": {
              "id": 61,
              "nom": "AGBANA",
              "prenoms": "John",
              "numeroTelephone": "98433212",
              "numeroPermis": "PERM-398401",
              "dateEtablissementPermis": 1707782400000,
              "lieuEtablissementPermis": "Lomé - Togo",
              "associationAffiliation": "RGI-ASSOC",
              "dateExpPermis": 1804896000000,
              "nationalite": "CNI-93382201",
              "dateNaissance": "1994-02-10",
              "genre": "homme",
              "createdBy": "Marco Transporteur",
              "createdAt": 1736806911921,
              "updateBy": null,
              "updateAt": 1736806911921
            },
            "immatriculation": "BF-23030",
            "chargeUtile": 1500,
            "capaciteAutorisee14": 1500,
            "nombreEssieu": 6,
            "dateExpVisiteTechnique": 1744934400000,
            "dateExpAssurance": 1743638400000,
            "pays": "BURKINA FASO",
            "nationalite": "Burkinabé",
            "marque": "MAN",
            "modeleCarteGrise": "Poids Lourd",
            "numeroCarteGrise": "0983223",
            "numeroCarteTransport": "345611",
            "disponible": true,
            "piecesJustificatives": null,
            "etatCamion": "VALIDER",
            "motifRejete": null,
            "createdBy": "Marco Transporteur",
            "createdAt": 1736808814253,
            "updateBy": "Marco Transporteur",
            "updateAt": 1736809037294
          },
          "affretement": {
            "id": 96,
            "declarationFret": {
              "id": 104,
              "declarant": {
                "id": 21,
                "maisonTransit": "GLORIA",
                "telephone": "91298899",
                "mail": "aggloria@gmail.com",
                "compteClient": "C464600",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818356,
                "updateBy": null,
                "updateAt": 1734371818356
              },
              "chargeur": {
                "id": 27,
                "nom": "Conseil des chargeurs CBC",
                "nationalite": "Burkinabé",
                "telephone": "91298899",
                "mail": "acbc@gmail.com",
                "repartitionFret": true,
                "compteClient": "C407000",
                "quotas": 0.6,
                "createdBy": "Conseil des chargeurs CBC",
                "createdAt": 1734373877310,
                "updateBy": null,
                "updateAt": 1734373877310
              },
              "destinataireMarchandise": {
                "id": 63,
                "nom": "BARRO'S",
                "email": "info@barros.com",
                "telephone": "+226 70 27 97 53",
                "nationalite": "Burkinabé",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818366,
                "updateBy": null,
                "updateAt": 1734371818366
              },
              "pieceJustificatives": null,
              "codeSh": "234",
              "natureMarchandise": "BLE",
              "produitGrandeConsommation": true,
              "sensTrafic": "IMP",
              "modeTransport": "Route",
              "origineMarchandise": "CHINE",
              "blNumeroConnaissement": "0009238881",
              "portEmbarquement": "PAL",
              "nomNavire": "NAVI-TRANS",
              "nationaliteNavire": "CHINOISE",
              "nombreCamionsSouhaite": 6,
              "prixTransportSouhaiteTonne": 35000,
              "affichagePrixRecepisse": true,
              "paysProvenance": "CHINE",
              "poidsMarchandise": 3000,
              "villeProvenance": "HONG KONG",
              "paysDestination": "BURKINA FASO",
              "villeDestination": "Ouagadougou",
              "createdBy": "C464600",
              "statutPayement": null,
              "statutAffretement": true,
              "etatMarchandise": "TRANSIT",
              "datePayement": null,
              "createdAt": 1736860911573,
              "updateBy": null,
              "updateAt": 1736861304096
            },
            "affretementCamions": null,
            "createdBy": "chargeur Client",
            "createdAt": 1736861304007,
            "updateBy": null,
            "updateAt": 1736861304007
          },
          "parametrage": {
            "id": 14,
            "chargeur": {
              "id": 27,
              "nom": "Conseil des chargeurs CBC",
              "nationalite": "Burkinabé",
              "telephone": "91298899",
              "mail": "acbc@gmail.com",
              "repartitionFret": true,
              "compteClient": "C407000",
              "quotas": 0.6,
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734373877310,
              "updateBy": null,
              "updateAt": 1734373877310
            },
            "nationalite": "Burkinabé",
            "quota": 0.6,
            "type": "TRANSIT",
            "createdBy": "Conseil des chargeurs CBC",
            "updateBy": null,
            "createdAt": 1736776199272,
            "updateAt": 1736776199272
          },
          "poids": 800
        },
        {
          "id": 8,
          "camion": {
            "id": 89,
            "transporteur": {
              "id": 45,
              "raisonSociale": "Marco Transporteur",
              "telephone": "91131955",
              "adresse": null,
              "mail": "transporteur013@gmail.com",
              "nif": null,
              "rccm": null,
              "licenceTransport": null,
              "createdBy": "Marco Transporteur",
              "createdAt": 1736181596124,
              "updateBy": null,
              "updateAt": 1736181596124
            },
            "conducteur": {
              "id": 22,
              "nom": "Soulemane",
              "prenoms": "Sankara",
              "numeroTelephone": "92 02 45 61",
              "numeroPermis": "850-20-45621",
              "dateEtablissementPermis": 1107369480000,
              "lieuEtablissementPermis": "Ouagadougou",
              "associationAffiliation": "UCRB",
              "dateExpPermis": 1736441715000,
              "nationalite": "CNI-65-123-0028",
              "dateNaissance": "1995-01-06T18:35",
              "genre": "homme",
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734374371455,
              "updateBy": null,
              "updateAt": 1734374371455
            },
            "immatriculation": "TG-0921",
            "chargeUtile": 300,
            "capaciteAutorisee14": 300,
            "nombreEssieu": 5,
            "dateExpVisiteTechnique": 1740182400000,
            "dateExpAssurance": 1741305600000,
            "pays": "TOGO",
            "nationalite": "Togolais",
            "marque": "MAN",
            "modeleCarteGrise": "Poids Lourd",
            "numeroCarteGrise": "0921934",
            "numeroCarteTransport": "CT-02823",
            "disponible": true,
            "piecesJustificatives": null,
            "etatCamion": "VALIDER",
            "motifRejete": null,
            "createdBy": "Marco Transporteur",
            "createdAt": 1736512982125,
            "updateBy": null,
            "updateAt": 1736513387965
          },
          "affretement": {
            "id": 96,
            "declarationFret": {
              "id": 104,
              "declarant": {
                "id": 21,
                "maisonTransit": "GLORIA",
                "telephone": "91298899",
                "mail": "aggloria@gmail.com",
                "compteClient": "C464600",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818356,
                "updateBy": null,
                "updateAt": 1734371818356
              },
              "chargeur": {
                "id": 27,
                "nom": "Conseil des chargeurs CBC",
                "nationalite": "Burkinabé",
                "telephone": "91298899",
                "mail": "acbc@gmail.com",
                "repartitionFret": true,
                "compteClient": "C407000",
                "quotas": 0.6,
                "createdBy": "Conseil des chargeurs CBC",
                "createdAt": 1734373877310,
                "updateBy": null,
                "updateAt": 1734373877310
              },
              "destinataireMarchandise": {
                "id": 63,
                "nom": "BARRO'S",
                "email": "info@barros.com",
                "telephone": "+226 70 27 97 53",
                "nationalite": "Burkinabé",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818366,
                "updateBy": null,
                "updateAt": 1734371818366
              },
              "pieceJustificatives": null,
              "codeSh": "234",
              "natureMarchandise": "BLE",
              "produitGrandeConsommation": true,
              "sensTrafic": "IMP",
              "modeTransport": "Route",
              "origineMarchandise": "CHINE",
              "blNumeroConnaissement": "0009238881",
              "portEmbarquement": "PAL",
              "nomNavire": "NAVI-TRANS",
              "nationaliteNavire": "CHINOISE",
              "nombreCamionsSouhaite": 6,
              "prixTransportSouhaiteTonne": 35000,
              "affichagePrixRecepisse": true,
              "paysProvenance": "CHINE",
              "poidsMarchandise": 3000,
              "villeProvenance": "HONG KONG",
              "paysDestination": "BURKINA FASO",
              "villeDestination": "Ouagadougou",
              "createdBy": "C464600",
              "statutPayement": null,
              "statutAffretement": true,
              "etatMarchandise": "TRANSIT",
              "datePayement": null,
              "createdAt": 1736860911573,
              "updateBy": null,
              "updateAt": 1736861304096
            },
            "affretementCamions": null,
            "createdBy": "chargeur Client",
            "createdAt": 1736861304007,
            "updateBy": null,
            "updateAt": 1736861304007
          },
          "parametrage": {
            "id": 15,
            "chargeur": {
              "id": 27,
              "nom": "Conseil des chargeurs CBC",
              "nationalite": "Burkinabé",
              "telephone": "91298899",
              "mail": "acbc@gmail.com",
              "repartitionFret": true,
              "compteClient": "C407000",
              "quotas": 0.6,
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734373877310,
              "updateBy": null,
              "updateAt": 1734373877310
            },
            "nationalite": "Togolaise",
            "quota": 0.4,
            "type": "TRANSIT",
            "createdBy": "Conseil des chargeurs CBC",
            "updateBy": null,
            "createdAt": 1736776199274,
            "updateAt": 1736776199274
          },
          "poids": 300
        },
        {
          "id": 9,
          "camion": {
            "id": 86,
            "transporteur": {
              "id": 45,
              "raisonSociale": "Marco Transporteur",
              "telephone": "91131955",
              "adresse": null,
              "mail": "transporteur013@gmail.com",
              "nif": null,
              "rccm": null,
              "licenceTransport": null,
              "createdBy": "Marco Transporteur",
              "createdAt": 1736181596124,
              "updateBy": null,
              "updateAt": 1736181596124
            },
            "conducteur": {
              "id": 23,
              "nom": "Ouedraogo",
              "prenoms": "troaré",
              "numeroTelephone": "92 32 45 55",
              "numeroPermis": "550-20-45300",
              "dateEtablissementPermis": 950814060000,
              "lieuEtablissementPermis": "Ouagadougou",
              "associationAffiliation": "URT",
              "dateExpPermis": 1736441708000,
              "nationalite": "CNI-70-123-0030",
              "dateNaissance": "1980-01-17T19:00",
              "genre": "homme",
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734375753622,
              "updateBy": null,
              "updateAt": 1734375753622
            },
            "immatriculation": "TG-8940",
            "chargeUtile": 1000,
            "capaciteAutorisee14": 1000,
            "nombreEssieu": 4,
            "dateExpVisiteTechnique": 1738281600000,
            "dateExpAssurance": 1738972800000,
            "pays": "TOGO",
            "nationalite": "Togolais",
            "marque": "MAN",
            "modeleCarteGrise": "Poids Lourd",
            "numeroCarteGrise": "098233112",
            "numeroCarteTransport": "CT-0993",
            "disponible": true,
            "piecesJustificatives": null,
            "etatCamion": "VALIDER",
            "motifRejete": null,
            "createdBy": "Marco Transporteur",
            "createdAt": 1736511894452,
            "updateBy": null,
            "updateAt": 1736513525358
          },
          "affretement": {
            "id": 96,
            "declarationFret": {
              "id": 104,
              "declarant": {
                "id": 21,
                "maisonTransit": "GLORIA",
                "telephone": "91298899",
                "mail": "aggloria@gmail.com",
                "compteClient": "C464600",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818356,
                "updateBy": null,
                "updateAt": 1734371818356
              },
              "chargeur": {
                "id": 27,
                "nom": "Conseil des chargeurs CBC",
                "nationalite": "Burkinabé",
                "telephone": "91298899",
                "mail": "acbc@gmail.com",
                "repartitionFret": true,
                "compteClient": "C407000",
                "quotas": 0.6,
                "createdBy": "Conseil des chargeurs CBC",
                "createdAt": 1734373877310,
                "updateBy": null,
                "updateAt": 1734373877310
              },
              "destinataireMarchandise": {
                "id": 63,
                "nom": "BARRO'S",
                "email": "info@barros.com",
                "telephone": "+226 70 27 97 53",
                "nationalite": "Burkinabé",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818366,
                "updateBy": null,
                "updateAt": 1734371818366
              },
              "pieceJustificatives": null,
              "codeSh": "234",
              "natureMarchandise": "BLE",
              "produitGrandeConsommation": true,
              "sensTrafic": "IMP",
              "modeTransport": "Route",
              "origineMarchandise": "CHINE",
              "blNumeroConnaissement": "0009238881",
              "portEmbarquement": "PAL",
              "nomNavire": "NAVI-TRANS",
              "nationaliteNavire": "CHINOISE",
              "nombreCamionsSouhaite": 6,
              "prixTransportSouhaiteTonne": 35000,
              "affichagePrixRecepisse": true,
              "paysProvenance": "CHINE",
              "poidsMarchandise": 3000,
              "villeProvenance": "HONG KONG",
              "paysDestination": "BURKINA FASO",
              "villeDestination": "Ouagadougou",
              "createdBy": "C464600",
              "statutPayement": null,
              "statutAffretement": true,
              "etatMarchandise": "TRANSIT",
              "datePayement": null,
              "createdAt": 1736860911573,
              "updateBy": null,
              "updateAt": 1736861304096
            },
            "affretementCamions": null,
            "createdBy": "chargeur Client",
            "createdAt": 1736861304007,
            "updateBy": null,
            "updateAt": 1736861304007
          },
          "parametrage": {
            "id": 15,
            "chargeur": {
              "id": 27,
              "nom": "Conseil des chargeurs CBC",
              "nationalite": "Burkinabé",
              "telephone": "91298899",
              "mail": "acbc@gmail.com",
              "repartitionFret": true,
              "compteClient": "C407000",
              "quotas": 0.6,
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734373877310,
              "updateBy": null,
              "updateAt": 1734373877310
            },
            "nationalite": "Togolaise",
            "quota": 0.4,
            "type": "TRANSIT",
            "createdBy": "Conseil des chargeurs CBC",
            "updateBy": null,
            "createdAt": 1736776199274,
            "updateAt": 1736776199274
          },
          "poids": 900
        }
      ],
      "createdBy": "chargeur Client",
      "createdAt": 1736861304007,
      "updateBy": null,
      "updateAt": 1736861304007
    },
    {
      "id": 95,
      "declarationFret": {
        "id": 85,
        "declarant": {
          "id": 21,
          "maisonTransit": "GLORIA",
          "telephone": "91298899",
          "mail": "aggloria@gmail.com",
          "compteClient": "C464600",
          "createdBy": "Gloria Gloria",
          "createdAt": 1734371818356,
          "updateBy": null,
          "updateAt": 1734371818356
        },
        "chargeur": {
          "id": 27,
          "nom": "Conseil des chargeurs CBC",
          "nationalite": "Burkinabé",
          "telephone": "91298899",
          "mail": "acbc@gmail.com",
          "repartitionFret": true,
          "compteClient": "C407000",
          "quotas": 0.6,
          "createdBy": "Conseil des chargeurs CBC",
          "createdAt": 1734373877310,
          "updateBy": null,
          "updateAt": 1734373877310
        },
        "destinataireMarchandise": {
          "id": 63,
          "nom": "BARRO'S",
          "email": "info@barros.com",
          "telephone": "+226 70 27 97 53",
          "nationalite": "Burkinabé",
          "createdBy": "Gloria Gloria",
          "createdAt": 1734371818366,
          "updateBy": null,
          "updateAt": 1734371818366
        },
        "pieceJustificatives": null,
        "codeSh": "5632",
        "natureMarchandise": "BLE",
        "produitGrandeConsommation": true,
        "sensTrafic": "EXP",
        "modeTransport": "Route",
        "origineMarchandise": "CHINE",
        "blNumeroConnaissement": "0948332321",
        "portEmbarquement": "PAL",
        "nomNavire": "NAVI-TRANS",
        "nationaliteNavire": "CHINOISE",
        "nombreCamionsSouhaite": 4,
        "prixTransportSouhaiteTonne": 45000,
        "affichagePrixRecepisse": true,
        "paysProvenance": "CHINE",
        "poidsMarchandise": 4000,
        "villeProvenance": "HONG KONG",
        "paysDestination": "BURKINA FASO",
        "villeDestination": "Ouagadougou",
        "createdBy": "C464600",
        "statutPayement": null,
        "statutAffretement": true,
        "etatMarchandise": "LOCAL",
        "datePayement": null,
        "createdAt": 1736524521056,
        "updateBy": null,
        "updateAt": 1736844703105
      },
      "affretementCamions": [
        {
          "id": 1,
          "camion": {
            "id": 103,
            "transporteur": {
              "id": 45,
              "raisonSociale": "Marco Transporteur",
              "telephone": "91131955",
              "adresse": null,
              "mail": "transporteur013@gmail.com",
              "nif": null,
              "rccm": null,
              "licenceTransport": null,
              "createdBy": "Marco Transporteur",
              "createdAt": 1736181596124,
              "updateBy": null,
              "updateAt": 1736181596124
            },
            "conducteur": {
              "id": 61,
              "nom": "AGBANA",
              "prenoms": "John",
              "numeroTelephone": "98433212",
              "numeroPermis": "PERM-398401",
              "dateEtablissementPermis": 1707782400000,
              "lieuEtablissementPermis": "Lomé - Togo",
              "associationAffiliation": "RGI-ASSOC",
              "dateExpPermis": 1804896000000,
              "nationalite": "CNI-93382201",
              "dateNaissance": "1994-02-10",
              "genre": "homme",
              "createdBy": "Marco Transporteur",
              "createdAt": 1736806911921,
              "updateBy": null,
              "updateAt": 1736806911921
            },
            "immatriculation": "BF-23030",
            "chargeUtile": 1500,
            "capaciteAutorisee14": 1500,
            "nombreEssieu": 6,
            "dateExpVisiteTechnique": 1744934400000,
            "dateExpAssurance": 1743638400000,
            "pays": "BURKINA FASO",
            "nationalite": "Burkinabé",
            "marque": "MAN",
            "modeleCarteGrise": "Poids Lourd",
            "numeroCarteGrise": "0983223",
            "numeroCarteTransport": "345611",
            "disponible": true,
            "piecesJustificatives": null,
            "etatCamion": "VALIDER",
            "motifRejete": null,
            "createdBy": "Marco Transporteur",
            "createdAt": 1736808814253,
            "updateBy": "Marco Transporteur",
            "updateAt": 1736809037294
          },
          "affretement": {
            "id": 95,
            "declarationFret": {
              "id": 85,
              "declarant": {
                "id": 21,
                "maisonTransit": "GLORIA",
                "telephone": "91298899",
                "mail": "aggloria@gmail.com",
                "compteClient": "C464600",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818356,
                "updateBy": null,
                "updateAt": 1734371818356
              },
              "chargeur": {
                "id": 27,
                "nom": "Conseil des chargeurs CBC",
                "nationalite": "Burkinabé",
                "telephone": "91298899",
                "mail": "acbc@gmail.com",
                "repartitionFret": true,
                "compteClient": "C407000",
                "quotas": 0.6,
                "createdBy": "Conseil des chargeurs CBC",
                "createdAt": 1734373877310,
                "updateBy": null,
                "updateAt": 1734373877310
              },
              "destinataireMarchandise": {
                "id": 63,
                "nom": "BARRO'S",
                "email": "info@barros.com",
                "telephone": "+226 70 27 97 53",
                "nationalite": "Burkinabé",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818366,
                "updateBy": null,
                "updateAt": 1734371818366
              },
              "pieceJustificatives": null,
              "codeSh": "5632",
              "natureMarchandise": "BLE",
              "produitGrandeConsommation": true,
              "sensTrafic": "EXP",
              "modeTransport": "Route",
              "origineMarchandise": "CHINE",
              "blNumeroConnaissement": "0948332321",
              "portEmbarquement": "PAL",
              "nomNavire": "NAVI-TRANS",
              "nationaliteNavire": "CHINOISE",
              "nombreCamionsSouhaite": 4,
              "prixTransportSouhaiteTonne": 45000,
              "affichagePrixRecepisse": true,
              "paysProvenance": "CHINE",
              "poidsMarchandise": 4000,
              "villeProvenance": "HONG KONG",
              "paysDestination": "BURKINA FASO",
              "villeDestination": "Ouagadougou",
              "createdBy": "C464600",
              "statutPayement": null,
              "statutAffretement": true,
              "etatMarchandise": "LOCAL",
              "datePayement": null,
              "createdAt": 1736524521056,
              "updateBy": null,
              "updateAt": 1736844703105
            },
            "affretementCamions": null,
            "createdBy": "chargeur Client",
            "createdAt": 1736844703042,
            "updateBy": null,
            "updateAt": 1736844703042
          },
          "parametrage": {
            "id": 14,
            "chargeur": {
              "id": 27,
              "nom": "Conseil des chargeurs CBC",
              "nationalite": "Burkinabé",
              "telephone": "91298899",
              "mail": "acbc@gmail.com",
              "repartitionFret": true,
              "compteClient": "C407000",
              "quotas": 0.6,
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734373877310,
              "updateBy": null,
              "updateAt": 1734373877310
            },
            "nationalite": "Burkinabé",
            "quota": 0.6,
            "type": "TRANSIT",
            "createdBy": "Conseil des chargeurs CBC",
            "updateBy": null,
            "createdAt": 1736776199272,
            "updateAt": 1736776199272
          },
          "poids": 1500
        },
        {
          "id": 2,
          "camion": {
            "id": 87,
            "transporteur": {
              "id": 45,
              "raisonSociale": "Marco Transporteur",
              "telephone": "91131955",
              "adresse": null,
              "mail": "transporteur013@gmail.com",
              "nif": null,
              "rccm": null,
              "licenceTransport": null,
              "createdBy": "Marco Transporteur",
              "createdAt": 1736181596124,
              "updateBy": null,
              "updateAt": 1736181596124
            },
            "conducteur": {
              "id": 24,
              "nom": "Campaoré",
              "prenoms": "Moussa",
              "numeroTelephone": "90 62 44 11",
              "numeroPermis": "960-80-45700",
              "dateEtablissementPermis": 1266087840000,
              "lieuEtablissementPermis": "Ouagadougou",
              "associationAffiliation": "URT",
              "dateExpPermis": 1736441698000,
              "nationalite": "CNI-82-123-0050",
              "dateNaissance": "1980-02-26T19:04",
              "genre": "homme",
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734375909750,
              "updateBy": null,
              "updateAt": 1734375909750
            },
            "immatriculation": "BF-94059",
            "chargeUtile": 400,
            "capaciteAutorisee14": 400,
            "nombreEssieu": 6,
            "dateExpVisiteTechnique": 1739059200000,
            "dateExpAssurance": 1739059200000,
            "pays": "BURKINA FASO",
            "nationalite": "Burkinabé",
            "marque": "MAN",
            "modeleCarteGrise": "Poids Lourd",
            "numeroCarteGrise": "07688832",
            "numeroCarteTransport": "CT-087592",
            "disponible": true,
            "piecesJustificatives": null,
            "etatCamion": "VALIDER",
            "motifRejete": null,
            "createdBy": "Marco Transporteur",
            "createdAt": 1736512177811,
            "updateBy": null,
            "updateAt": 1736513514018
          },
          "affretement": {
            "id": 95,
            "declarationFret": {
              "id": 85,
              "declarant": {
                "id": 21,
                "maisonTransit": "GLORIA",
                "telephone": "91298899",
                "mail": "aggloria@gmail.com",
                "compteClient": "C464600",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818356,
                "updateBy": null,
                "updateAt": 1734371818356
              },
              "chargeur": {
                "id": 27,
                "nom": "Conseil des chargeurs CBC",
                "nationalite": "Burkinabé",
                "telephone": "91298899",
                "mail": "acbc@gmail.com",
                "repartitionFret": true,
                "compteClient": "C407000",
                "quotas": 0.6,
                "createdBy": "Conseil des chargeurs CBC",
                "createdAt": 1734373877310,
                "updateBy": null,
                "updateAt": 1734373877310
              },
              "destinataireMarchandise": {
                "id": 63,
                "nom": "BARRO'S",
                "email": "info@barros.com",
                "telephone": "+226 70 27 97 53",
                "nationalite": "Burkinabé",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818366,
                "updateBy": null,
                "updateAt": 1734371818366
              },
              "pieceJustificatives": null,
              "codeSh": "5632",
              "natureMarchandise": "BLE",
              "produitGrandeConsommation": true,
              "sensTrafic": "EXP",
              "modeTransport": "Route",
              "origineMarchandise": "CHINE",
              "blNumeroConnaissement": "0948332321",
              "portEmbarquement": "PAL",
              "nomNavire": "NAVI-TRANS",
              "nationaliteNavire": "CHINOISE",
              "nombreCamionsSouhaite": 4,
              "prixTransportSouhaiteTonne": 45000,
              "affichagePrixRecepisse": true,
              "paysProvenance": "CHINE",
              "poidsMarchandise": 4000,
              "villeProvenance": "HONG KONG",
              "paysDestination": "BURKINA FASO",
              "villeDestination": "Ouagadougou",
              "createdBy": "C464600",
              "statutPayement": null,
              "statutAffretement": true,
              "etatMarchandise": "LOCAL",
              "datePayement": null,
              "createdAt": 1736524521056,
              "updateBy": null,
              "updateAt": 1736844703105
            },
            "affretementCamions": null,
            "createdBy": "chargeur Client",
            "createdAt": 1736844703042,
            "updateBy": null,
            "updateAt": 1736844703042
          },
          "parametrage": {
            "id": 14,
            "chargeur": {
              "id": 27,
              "nom": "Conseil des chargeurs CBC",
              "nationalite": "Burkinabé",
              "telephone": "91298899",
              "mail": "acbc@gmail.com",
              "repartitionFret": true,
              "compteClient": "C407000",
              "quotas": 0.6,
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734373877310,
              "updateBy": null,
              "updateAt": 1734373877310
            },
            "nationalite": "Burkinabé",
            "quota": 0.6,
            "type": "TRANSIT",
            "createdBy": "Conseil des chargeurs CBC",
            "updateBy": null,
            "createdAt": 1736776199272,
            "updateAt": 1736776199272
          },
          "poids": 400
        },
        {
          "id": 3,
          "camion": {
            "id": 85,
            "transporteur": {
              "id": 45,
              "raisonSociale": "Marco Transporteur",
              "telephone": "91131955",
              "adresse": null,
              "mail": "transporteur013@gmail.com",
              "nif": null,
              "rccm": null,
              "licenceTransport": null,
              "createdBy": "Marco Transporteur",
              "createdAt": 1736181596124,
              "updateBy": null,
              "updateAt": 1736181596124
            },
            "conducteur": {
              "id": 22,
              "nom": "Soulemane",
              "prenoms": "Sankara",
              "numeroTelephone": "92 02 45 61",
              "numeroPermis": "850-20-45621",
              "dateEtablissementPermis": 1107369480000,
              "lieuEtablissementPermis": "Ouagadougou",
              "associationAffiliation": "UCRB",
              "dateExpPermis": 1736441715000,
              "nationalite": "CNI-65-123-0028",
              "dateNaissance": "1995-01-06T18:35",
              "genre": "homme",
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734374371455,
              "updateBy": null,
              "updateAt": 1734374371455
            },
            "immatriculation": "BF-33291",
            "chargeUtile": 2000,
            "capaciteAutorisee14": 2000,
            "nombreEssieu": 4,
            "dateExpVisiteTechnique": 1737763200000,
            "dateExpAssurance": 1738281600000,
            "pays": "BURKINA FASO",
            "nationalite": "Burkinabé",
            "marque": "MAN",
            "modeleCarteGrise": "Poids Lourd",
            "numeroCarteGrise": "0129993",
            "numeroCarteTransport": "CT-0931",
            "disponible": true,
            "piecesJustificatives": null,
            "etatCamion": "VALIDER",
            "motifRejete": null,
            "createdBy": "Marco Transporteur",
            "createdAt": 1736511480644,
            "updateBy": "Marco Transporteur",
            "updateAt": 1736809106851
          },
          "affretement": {
            "id": 95,
            "declarationFret": {
              "id": 85,
              "declarant": {
                "id": 21,
                "maisonTransit": "GLORIA",
                "telephone": "91298899",
                "mail": "aggloria@gmail.com",
                "compteClient": "C464600",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818356,
                "updateBy": null,
                "updateAt": 1734371818356
              },
              "chargeur": {
                "id": 27,
                "nom": "Conseil des chargeurs CBC",
                "nationalite": "Burkinabé",
                "telephone": "91298899",
                "mail": "acbc@gmail.com",
                "repartitionFret": true,
                "compteClient": "C407000",
                "quotas": 0.6,
                "createdBy": "Conseil des chargeurs CBC",
                "createdAt": 1734373877310,
                "updateBy": null,
                "updateAt": 1734373877310
              },
              "destinataireMarchandise": {
                "id": 63,
                "nom": "BARRO'S",
                "email": "info@barros.com",
                "telephone": "+226 70 27 97 53",
                "nationalite": "Burkinabé",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818366,
                "updateBy": null,
                "updateAt": 1734371818366
              },
              "pieceJustificatives": null,
              "codeSh": "5632",
              "natureMarchandise": "BLE",
              "produitGrandeConsommation": true,
              "sensTrafic": "EXP",
              "modeTransport": "Route",
              "origineMarchandise": "CHINE",
              "blNumeroConnaissement": "0948332321",
              "portEmbarquement": "PAL",
              "nomNavire": "NAVI-TRANS",
              "nationaliteNavire": "CHINOISE",
              "nombreCamionsSouhaite": 4,
              "prixTransportSouhaiteTonne": 45000,
              "affichagePrixRecepisse": true,
              "paysProvenance": "CHINE",
              "poidsMarchandise": 4000,
              "villeProvenance": "HONG KONG",
              "paysDestination": "BURKINA FASO",
              "villeDestination": "Ouagadougou",
              "createdBy": "C464600",
              "statutPayement": null,
              "statutAffretement": true,
              "etatMarchandise": "LOCAL",
              "datePayement": null,
              "createdAt": 1736524521056,
              "updateBy": null,
              "updateAt": 1736844703105
            },
            "affretementCamions": null,
            "createdBy": "chargeur Client",
            "createdAt": 1736844703042,
            "updateBy": null,
            "updateAt": 1736844703042
          },
          "parametrage": {
            "id": 14,
            "chargeur": {
              "id": 27,
              "nom": "Conseil des chargeurs CBC",
              "nationalite": "Burkinabé",
              "telephone": "91298899",
              "mail": "acbc@gmail.com",
              "repartitionFret": true,
              "compteClient": "C407000",
              "quotas": 0.6,
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734373877310,
              "updateBy": null,
              "updateAt": 1734373877310
            },
            "nationalite": "Burkinabé",
            "quota": 0.6,
            "type": "TRANSIT",
            "createdBy": "Conseil des chargeurs CBC",
            "updateBy": null,
            "createdAt": 1736776199272,
            "updateAt": 1736776199272
          },
          "poids": 500
        },
        {
          "id": 4,
          "camion": {
            "id": 102,
            "transporteur": {
              "id": 45,
              "raisonSociale": "Marco Transporteur",
              "telephone": "91131955",
              "adresse": null,
              "mail": "transporteur013@gmail.com",
              "nif": null,
              "rccm": null,
              "licenceTransport": null,
              "createdBy": "Marco Transporteur",
              "createdAt": 1736181596124,
              "updateBy": null,
              "updateAt": 1736181596124
            },
            "conducteur": {
              "id": 61,
              "nom": "AGBANA",
              "prenoms": "John",
              "numeroTelephone": "98433212",
              "numeroPermis": "PERM-398401",
              "dateEtablissementPermis": 1707782400000,
              "lieuEtablissementPermis": "Lomé - Togo",
              "associationAffiliation": "RGI-ASSOC",
              "dateExpPermis": 1804896000000,
              "nationalite": "CNI-93382201",
              "dateNaissance": "1994-02-10",
              "genre": "homme",
              "createdBy": "Marco Transporteur",
              "createdAt": 1736806911921,
              "updateBy": null,
              "updateAt": 1736806911921
            },
            "immatriculation": "TG-00291",
            "chargeUtile": 2000,
            "capaciteAutorisee14": 2000,
            "nombreEssieu": 4,
            "dateExpVisiteTechnique": 1745539200000,
            "dateExpAssurance": 1745020800000,
            "pays": "TOGO",
            "nationalite": "Togolais",
            "marque": "MAN",
            "modeleCarteGrise": "Poids Lourd",
            "numeroCarteGrise": "0923921",
            "numeroCarteTransport": "0193372",
            "disponible": true,
            "piecesJustificatives": null,
            "etatCamion": "VALIDER",
            "motifRejete": null,
            "createdBy": "Marco Transporteur",
            "createdAt": 1736808673573,
            "updateBy": "Marco Transporteur",
            "updateAt": 1736808881508
          },
          "affretement": {
            "id": 95,
            "declarationFret": {
              "id": 85,
              "declarant": {
                "id": 21,
                "maisonTransit": "GLORIA",
                "telephone": "91298899",
                "mail": "aggloria@gmail.com",
                "compteClient": "C464600",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818356,
                "updateBy": null,
                "updateAt": 1734371818356
              },
              "chargeur": {
                "id": 27,
                "nom": "Conseil des chargeurs CBC",
                "nationalite": "Burkinabé",
                "telephone": "91298899",
                "mail": "acbc@gmail.com",
                "repartitionFret": true,
                "compteClient": "C407000",
                "quotas": 0.6,
                "createdBy": "Conseil des chargeurs CBC",
                "createdAt": 1734373877310,
                "updateBy": null,
                "updateAt": 1734373877310
              },
              "destinataireMarchandise": {
                "id": 63,
                "nom": "BARRO'S",
                "email": "info@barros.com",
                "telephone": "+226 70 27 97 53",
                "nationalite": "Burkinabé",
                "createdBy": "Gloria Gloria",
                "createdAt": 1734371818366,
                "updateBy": null,
                "updateAt": 1734371818366
              },
              "pieceJustificatives": null,
              "codeSh": "5632",
              "natureMarchandise": "BLE",
              "produitGrandeConsommation": true,
              "sensTrafic": "EXP",
              "modeTransport": "Route",
              "origineMarchandise": "CHINE",
              "blNumeroConnaissement": "0948332321",
              "portEmbarquement": "PAL",
              "nomNavire": "NAVI-TRANS",
              "nationaliteNavire": "CHINOISE",
              "nombreCamionsSouhaite": 4,
              "prixTransportSouhaiteTonne": 45000,
              "affichagePrixRecepisse": true,
              "paysProvenance": "CHINE",
              "poidsMarchandise": 4000,
              "villeProvenance": "HONG KONG",
              "paysDestination": "BURKINA FASO",
              "villeDestination": "Ouagadougou",
              "createdBy": "C464600",
              "statutPayement": null,
              "statutAffretement": true,
              "etatMarchandise": "LOCAL",
              "datePayement": null,
              "createdAt": 1736524521056,
              "updateBy": null,
              "updateAt": 1736844703105
            },
            "affretementCamions": null,
            "createdBy": "chargeur Client",
            "createdAt": 1736844703042,
            "updateBy": null,
            "updateAt": 1736844703042
          },
          "parametrage": {
            "id": 15,
            "chargeur": {
              "id": 27,
              "nom": "Conseil des chargeurs CBC",
              "nationalite": "Burkinabé",
              "telephone": "91298899",
              "mail": "acbc@gmail.com",
              "repartitionFret": true,
              "compteClient": "C407000",
              "quotas": 0.6,
              "createdBy": "Conseil des chargeurs CBC",
              "createdAt": 1734373877310,
              "updateBy": null,
              "updateAt": 1734373877310
            },
            "nationalite": "Togolaise",
            "quota": 0.4,
            "type": "TRANSIT",
            "createdBy": "Conseil des chargeurs CBC",
            "updateBy": null,
            "createdAt": 1736776199274,
            "updateAt": 1736776199274
          },
          "poids": 1600
        }
      ],
      "createdBy": "chargeur Client",
      "createdAt": 1736844703042,
      "updateBy": null,
      "updateAt": 1736844703042
    }
  ],
  "message": "La liste des affretements réalisés",
  "status": 200
}

export interface AffretementDetailModel {
  id: number;
  declarationFret: DeclarationFretModel;
  affretementCamions: AffretementCamionModel[];
  etatAffretement: boolean;
  motifRejet: string;
  createdAt: Date;
  updatedAt: Date;
  createdBy: string;
  updatedBy: string;
}

export interface AffretementCamionModel {
  id: number;
  camion: CamionModel;
  affretement: AffretementModel;
  parametrage: ParametrageModel;
  poids: number;
  etatBon: boolean;
  etatBonChargeur: boolean;
  fileUrl: string;
  statusPayment: boolean | null;
}


const affretement = {
  "id": 96,
  "declarationFret": {
    "id": 104,
    "declarant": {
      "id": 21,
      "maisonTransit": "GLORIA",
      "telephone": "91298899",
      "mail": "aggloria@gmail.com",
      "compteClient": "C464600",
      "createdBy": "Gloria Gloria",
      "createdAt": 1734371818356,
      "updateBy": null,
      "updateAt": 1734371818356
    },
    "chargeur": {
      "id": 27,
      "nom": "Conseil des chargeurs CBC",
      "nationalite": "Burkinabé",
      "telephone": "91298899",
      "mail": "acbc@gmail.com",
      "repartitionFret": true,
      "compteClient": "C407000",
      "quotas": 0.6,
      "createdBy": "Conseil des chargeurs CBC",
      "createdAt": 1734373877310,
      "updateBy": null,
      "updateAt": 1734373877310
    },
    "destinataireMarchandise": {
      "id": 63,
      "nom": "BARRO'S",
      "email": "info@barros.com",
      "telephone": "+226 70 27 97 53",
      "nationalite": "Burkinabé",
      "createdBy": "Gloria Gloria",
      "createdAt": 1734371818366,
      "updateBy": null,
      "updateAt": 1734371818366
    },
    "pieceJustificatives": null,
    "codeSh": "234",
    "natureMarchandise": "BLE",
    "produitGrandeConsommation": true,
    "sensTrafic": "IMP",
    "modeTransport": "Route",
    "origineMarchandise": "CHINE",
    "blNumeroConnaissement": "0009238881",
    "portEmbarquement": "PAL",
    "nomNavire": "NAVI-TRANS",
    "nationaliteNavire": "CHINOISE",
    "nombreCamionsSouhaite": 6,
    "prixTransportSouhaiteTonne": 35000,
    "affichagePrixRecepisse": true,
    "paysProvenance": "CHINE",
    "poidsMarchandise": 3000,
    "villeProvenance": "HONG KONG",
    "paysDestination": "BURKINA FASO",
    "villeDestination": "Ouagadougou",
    "createdBy": "C464600",
    "statutPayement": null,
    "statutAffretement": true,
    "etatMarchandise": "TRANSIT",
    "datePayement": null,
    "createdAt": 1736860911573,
    "updateBy": null,
    "updateAt": 1736861304096
  },
  "affretementCamions": [
    {
      "id": 5,
      "camion":   {
        "id": 87,
        "transporteur": {
          "id": 45,
          "raisonSociale": "Marco Transporteur",
          "telephone": "91131955",
          "adresse": null,
          "mail": "transporteur013@gmail.com",
          "nif": null,
          "rccm": null,
          "licenceTransport": null,
          "createdBy": "Marco Transporteur",
          "createdAt": 1736181596124,
          "updateBy": null,
          "updateAt": 1736181596124
        },
        "conducteur": {
          "id": 24,
          "nom": "Campaoré",
          "prenoms": "Moussa",
          "numeroTelephone": "90 62 44 11",
          "numeroPermis": "960-80-45700",
          "dateEtablissementPermis": 1266087840000,
          "lieuEtablissementPermis": "Ouagadougou",
          "associationAffiliation": "URT",
          "dateExpPermis": 1736441698000,
          "nationalite": "CNI-82-123-0050",
          "dateNaissance": "1980-02-26T19:04",
          "genre": "homme",
          "createdBy": "Conseil des chargeurs CBC",
          "createdAt": 1734375909750,
          "updateBy": null,
          "updateAt": 1734375909750
        },
        "immatriculation": "BF-94059",
        "chargeUtile": 400,
        "capaciteAutorisee14": 400,
        "nombreEssieu": 6,
        "dateExpVisiteTechnique": 1739059200000,
        "dateExpAssurance": 1739059200000,
        "pays": "BURKINA FASO",
        "nationalite": "Burkinabé",
        "marque": "MAN",
        "modeleCarteGrise": "Poids Lourd",
        "numeroCarteGrise": "07688832",
        "numeroCarteTransport": "CT-087592",
        "disponible": true,
        "piecesJustificatives": null,
        "etatCamion": "VALIDER",
        "motifRejete": null,
        "createdBy": "Marco Transporteur",
        "createdAt": 1736512177811,
        "updateBy": null,
        "updateAt": 1736513514018
      },
      "affretement": {
        "id": 96,
        "declarationFret": {
          "id": 104,
          "declarant": {
            "id": 21,
            "maisonTransit": "GLORIA",
            "telephone": "91298899",
            "mail": "aggloria@gmail.com",
            "compteClient": "C464600",
            "createdBy": "Gloria Gloria",
            "createdAt": 1734371818356,
            "updateBy": null,
            "updateAt": 1734371818356
          },
          "chargeur": {
            "id": 27,
            "nom": "Conseil des chargeurs CBC",
            "nationalite": "Burkinabé",
            "telephone": "91298899",
            "mail": "acbc@gmail.com",
            "repartitionFret": true,
            "compteClient": "C407000",
            "quotas": 0.6,
            "createdBy": "Conseil des chargeurs CBC",
            "createdAt": 1734373877310,
            "updateBy": null,
            "updateAt": 1734373877310
          },
          "destinataireMarchandise": {
            "id": 63,
            "nom": "BARRO'S",
            "email": "info@barros.com",
            "telephone": "+226 70 27 97 53",
            "nationalite": "Burkinabé",
            "createdBy": "Gloria Gloria",
            "createdAt": 1734371818366,
            "updateBy": null,
            "updateAt": 1734371818366
          },
          "pieceJustificatives": null,
          "codeSh": "234",
          "natureMarchandise": "BLE",
          "produitGrandeConsommation": true,
          "sensTrafic": "IMP",
          "modeTransport": "Route",
          "origineMarchandise": "CHINE",
          "blNumeroConnaissement": "0009238881",
          "portEmbarquement": "PAL",
          "nomNavire": "NAVI-TRANS",
          "nationaliteNavire": "CHINOISE",
          "nombreCamionsSouhaite": 6,
          "prixTransportSouhaiteTonne": 35000,
          "affichagePrixRecepisse": true,
          "paysProvenance": "CHINE",
          "poidsMarchandise": 3000,
          "villeProvenance": "HONG KONG",
          "paysDestination": "BURKINA FASO",
          "villeDestination": "Ouagadougou",
          "createdBy": "C464600",
          "statutPayement": null,
          "statutAffretement": true,
          "etatMarchandise": "TRANSIT",
          "datePayement": null,
          "createdAt": 1736860911573,
          "updateBy": null,
          "updateAt": 1736861304096
        },
        "affretementCamions": null,
        "createdBy": "chargeur Client",
        "createdAt": 1736861304007,
        "updateBy": null,
        "updateAt": 1736861304007
      },
      "parametrage": {
        "id": 14,
        "chargeur": {
          "id": 27,
          "nom": "Conseil des chargeurs CBC",
          "nationalite": "Burkinabé",
          "telephone": "91298899",
          "mail": "acbc@gmail.com",
          "repartitionFret": true,
          "compteClient": "C407000",
          "quotas": 0.6,
          "createdBy": "Conseil des chargeurs CBC",
          "createdAt": 1734373877310,
          "updateBy": null,
          "updateAt": 1734373877310
        },
        "nationalite": "Burkinabé",
        "quota": 0.6,
        "type": "TRANSIT",
        "createdBy": "Conseil des chargeurs CBC",
        "updateBy": null,
        "createdAt": 1736776199272,
        "updateAt": 1736776199272
      },
      "poids": 400
    },
    {
      "id": 6,
      "camion": {
        "id": 88,
        "transporteur": {
          "id": 45,
          "raisonSociale": "Marco Transporteur",
          "telephone": "91131955",
          "adresse": null,
          "mail": "transporteur013@gmail.com",
          "nif": null,
          "rccm": null,
          "licenceTransport": null,
          "createdBy": "Marco Transporteur",
          "createdAt": 1736181596124,
          "updateBy": null,
          "updateAt": 1736181596124
        },
        "conducteur": {
          "id": 23,
          "nom": "Ouedraogo",
          "prenoms": "troaré",
          "numeroTelephone": "92 32 45 55",
          "numeroPermis": "550-20-45300",
          "dateEtablissementPermis": 950814060000,
          "lieuEtablissementPermis": "Ouagadougou",
          "associationAffiliation": "URT",
          "dateExpPermis": 1736441708000,
          "nationalite": "CNI-70-123-0030",
          "dateNaissance": "1980-01-17T19:00",
          "genre": "homme",
          "createdBy": "Conseil des chargeurs CBC",
          "createdAt": 1734375753622,
          "updateBy": null,
          "updateAt": 1734375753622
        },
        "immatriculation": "BF-9810",
        "chargeUtile": 600,
        "capaciteAutorisee14": 600,
        "nombreEssieu": 6,
        "dateExpVisiteTechnique": 1739059200000,
        "dateExpAssurance": 1739059200000,
        "pays": "BURKINA FASO",
        "nationalite": "Burkinabé",
        "marque": "MAN",
        "modeleCarteGrise": "Poids Lourd",
        "numeroCarteGrise": "099281",
        "numeroCarteTransport": "CT-09943",
        "disponible": true,
        "piecesJustificatives": null,
        "etatCamion": "VALIDER",
        "motifRejete": null,
        "createdBy": "Marco Transporteur",
        "createdAt": 1736512414515,
        "updateBy": null,
        "updateAt": 1736513411318
      },
      "affretement": {
        "id": 96,
        "declarationFret": {
          "id": 104,
          "declarant": {
            "id": 21,
            "maisonTransit": "GLORIA",
            "telephone": "91298899",
            "mail": "aggloria@gmail.com",
            "compteClient": "C464600",
            "createdBy": "Gloria Gloria",
            "createdAt": 1734371818356,
            "updateBy": null,
            "updateAt": 1734371818356
          },
          "chargeur": {
            "id": 27,
            "nom": "Conseil des chargeurs CBC",
            "nationalite": "Burkinabé",
            "telephone": "91298899",
            "mail": "acbc@gmail.com",
            "repartitionFret": true,
            "compteClient": "C407000",
            "quotas": 0.6,
            "createdBy": "Conseil des chargeurs CBC",
            "createdAt": 1734373877310,
            "updateBy": null,
            "updateAt": 1734373877310
          },
          "destinataireMarchandise": {
            "id": 63,
            "nom": "BARRO'S",
            "email": "info@barros.com",
            "telephone": "+226 70 27 97 53",
            "nationalite": "Burkinabé",
            "createdBy": "Gloria Gloria",
            "createdAt": 1734371818366,
            "updateBy": null,
            "updateAt": 1734371818366
          },
          "pieceJustificatives": null,
          "codeSh": "234",
          "natureMarchandise": "BLE",
          "produitGrandeConsommation": true,
          "sensTrafic": "IMP",
          "modeTransport": "Route",
          "origineMarchandise": "CHINE",
          "blNumeroConnaissement": "0009238881",
          "portEmbarquement": "PAL",
          "nomNavire": "NAVI-TRANS",
          "nationaliteNavire": "CHINOISE",
          "nombreCamionsSouhaite": 6,
          "prixTransportSouhaiteTonne": 35000,
          "affichagePrixRecepisse": true,
          "paysProvenance": "CHINE",
          "poidsMarchandise": 3000,
          "villeProvenance": "HONG KONG",
          "paysDestination": "BURKINA FASO",
          "villeDestination": "Ouagadougou",
          "createdBy": "C464600",
          "statutPayement": null,
          "statutAffretement": true,
          "etatMarchandise": "TRANSIT",
          "datePayement": null,
          "createdAt": 1736860911573,
          "updateBy": null,
          "updateAt": 1736861304096
        },
        "affretementCamions": null,
        "createdBy": "chargeur Client",
        "createdAt": 1736861304007,
        "updateBy": null,
        "updateAt": 1736861304007
      },
      "parametrage": {
        "id": 14,
        "chargeur": {
          "id": 27,
          "nom": "Conseil des chargeurs CBC",
          "nationalite": "Burkinabé",
          "telephone": "91298899",
          "mail": "acbc@gmail.com",
          "repartitionFret": true,
          "compteClient": "C407000",
          "quotas": 0.6,
          "createdBy": "Conseil des chargeurs CBC",
          "createdAt": 1734373877310,
          "updateBy": null,
          "updateAt": 1734373877310
        },
        "nationalite": "Burkinabé",
        "quota": 0.6,
        "type": "TRANSIT",
        "createdBy": "Conseil des chargeurs CBC",
        "updateBy": null,
        "createdAt": 1736776199272,
        "updateAt": 1736776199272
      },
      "poids": 600
    },
    {
      "id": 7,
      "camion": {
        "id": 103,
        "transporteur": {
          "id": 45,
          "raisonSociale": "Marco Transporteur",
          "telephone": "91131955",
          "adresse": null,
          "mail": "transporteur013@gmail.com",
          "nif": null,
          "rccm": null,
          "licenceTransport": null,
          "createdBy": "Marco Transporteur",
          "createdAt": 1736181596124,
          "updateBy": null,
          "updateAt": 1736181596124
        },
        "conducteur": {
          "id": 61,
          "nom": "AGBANA",
          "prenoms": "John",
          "numeroTelephone": "98433212",
          "numeroPermis": "PERM-398401",
          "dateEtablissementPermis": 1707782400000,
          "lieuEtablissementPermis": "Lomé - Togo",
          "associationAffiliation": "RGI-ASSOC",
          "dateExpPermis": 1804896000000,
          "nationalite": "CNI-93382201",
          "dateNaissance": "1994-02-10",
          "genre": "homme",
          "createdBy": "Marco Transporteur",
          "createdAt": 1736806911921,
          "updateBy": null,
          "updateAt": 1736806911921
        },
        "immatriculation": "BF-23030",
        "chargeUtile": 1500,
        "capaciteAutorisee14": 1500,
        "nombreEssieu": 6,
        "dateExpVisiteTechnique": 1744934400000,
        "dateExpAssurance": 1743638400000,
        "pays": "BURKINA FASO",
        "nationalite": "Burkinabé",
        "marque": "MAN",
        "modeleCarteGrise": "Poids Lourd",
        "numeroCarteGrise": "0983223",
        "numeroCarteTransport": "345611",
        "disponible": true,
        "piecesJustificatives": null,
        "etatCamion": "VALIDER",
        "motifRejete": null,
        "createdBy": "Marco Transporteur",
        "createdAt": 1736808814253,
        "updateBy": "Marco Transporteur",
        "updateAt": 1736809037294
      },
      "affretement": {
        "id": 96,
        "declarationFret": {
          "id": 104,
          "declarant": {
            "id": 21,
            "maisonTransit": "GLORIA",
            "telephone": "91298899",
            "mail": "aggloria@gmail.com",
            "compteClient": "C464600",
            "createdBy": "Gloria Gloria",
            "createdAt": 1734371818356,
            "updateBy": null,
            "updateAt": 1734371818356
          },
          "chargeur": {
            "id": 27,
            "nom": "Conseil des chargeurs CBC",
            "nationalite": "Burkinabé",
            "telephone": "91298899",
            "mail": "acbc@gmail.com",
            "repartitionFret": true,
            "compteClient": "C407000",
            "quotas": 0.6,
            "createdBy": "Conseil des chargeurs CBC",
            "createdAt": 1734373877310,
            "updateBy": null,
            "updateAt": 1734373877310
          },
          "destinataireMarchandise": {
            "id": 63,
            "nom": "BARRO'S",
            "email": "info@barros.com",
            "telephone": "+226 70 27 97 53",
            "nationalite": "Burkinabé",
            "createdBy": "Gloria Gloria",
            "createdAt": 1734371818366,
            "updateBy": null,
            "updateAt": 1734371818366
          },
          "pieceJustificatives": null,
          "codeSh": "234",
          "natureMarchandise": "BLE",
          "produitGrandeConsommation": true,
          "sensTrafic": "IMP",
          "modeTransport": "Route",
          "origineMarchandise": "CHINE",
          "blNumeroConnaissement": "0009238881",
          "portEmbarquement": "PAL",
          "nomNavire": "NAVI-TRANS",
          "nationaliteNavire": "CHINOISE",
          "nombreCamionsSouhaite": 6,
          "prixTransportSouhaiteTonne": 35000,
          "affichagePrixRecepisse": true,
          "paysProvenance": "CHINE",
          "poidsMarchandise": 3000,
          "villeProvenance": "HONG KONG",
          "paysDestination": "BURKINA FASO",
          "villeDestination": "Ouagadougou",
          "createdBy": "C464600",
          "statutPayement": null,
          "statutAffretement": true,
          "etatMarchandise": "TRANSIT",
          "datePayement": null,
          "createdAt": 1736860911573,
          "updateBy": null,
          "updateAt": 1736861304096
        },
        "affretementCamions": null,
        "createdBy": "chargeur Client",
        "createdAt": 1736861304007,
        "updateBy": null,
        "updateAt": 1736861304007
      },
      "parametrage": {
        "id": 14,
        "chargeur": {
          "id": 27,
          "nom": "Conseil des chargeurs CBC",
          "nationalite": "Burkinabé",
          "telephone": "91298899",
          "mail": "acbc@gmail.com",
          "repartitionFret": true,
          "compteClient": "C407000",
          "quotas": 0.6,
          "createdBy": "Conseil des chargeurs CBC",
          "createdAt": 1734373877310,
          "updateBy": null,
          "updateAt": 1734373877310
        },
        "nationalite": "Burkinabé",
        "quota": 0.6,
        "type": "TRANSIT",
        "createdBy": "Conseil des chargeurs CBC",
        "updateBy": null,
        "createdAt": 1736776199272,
        "updateAt": 1736776199272
      },
      "poids": 800
    },
    {
      "id": 8,
      "camion": {
        "id": 89,
        "transporteur": {
          "id": 45,
          "raisonSociale": "Marco Transporteur",
          "telephone": "91131955",
          "adresse": null,
          "mail": "transporteur013@gmail.com",
          "nif": null,
          "rccm": null,
          "licenceTransport": null,
          "createdBy": "Marco Transporteur",
          "createdAt": 1736181596124,
          "updateBy": null,
          "updateAt": 1736181596124
        },
        "conducteur": {
          "id": 22,
          "nom": "Soulemane",
          "prenoms": "Sankara",
          "numeroTelephone": "92 02 45 61",
          "numeroPermis": "850-20-45621",
          "dateEtablissementPermis": 1107369480000,
          "lieuEtablissementPermis": "Ouagadougou",
          "associationAffiliation": "UCRB",
          "dateExpPermis": 1736441715000,
          "nationalite": "CNI-65-123-0028",
          "dateNaissance": "1995-01-06T18:35",
          "genre": "homme",
          "createdBy": "Conseil des chargeurs CBC",
          "createdAt": 1734374371455,
          "updateBy": null,
          "updateAt": 1734374371455
        },
        "immatriculation": "TG-0921",
        "chargeUtile": 300,
        "capaciteAutorisee14": 300,
        "nombreEssieu": 5,
        "dateExpVisiteTechnique": 1740182400000,
        "dateExpAssurance": 1741305600000,
        "pays": "TOGO",
        "nationalite": "Togolais",
        "marque": "MAN",
        "modeleCarteGrise": "Poids Lourd",
        "numeroCarteGrise": "0921934",
        "numeroCarteTransport": "CT-02823",
        "disponible": true,
        "piecesJustificatives": null,
        "etatCamion": "VALIDER",
        "motifRejete": null,
        "createdBy": "Marco Transporteur",
        "createdAt": 1736512982125,
        "updateBy": null,
        "updateAt": 1736513387965
      },
      "affretement": {
        "id": 96,
        "declarationFret": {
          "id": 104,
          "declarant": {
            "id": 21,
            "maisonTransit": "GLORIA",
            "telephone": "91298899",
            "mail": "aggloria@gmail.com",
            "compteClient": "C464600",
            "createdBy": "Gloria Gloria",
            "createdAt": 1734371818356,
            "updateBy": null,
            "updateAt": 1734371818356
          },
          "chargeur": {
            "id": 27,
            "nom": "Conseil des chargeurs CBC",
            "nationalite": "Burkinabé",
            "telephone": "91298899",
            "mail": "acbc@gmail.com",
            "repartitionFret": true,
            "compteClient": "C407000",
            "quotas": 0.6,
            "createdBy": "Conseil des chargeurs CBC",
            "createdAt": 1734373877310,
            "updateBy": null,
            "updateAt": 1734373877310
          },
          "destinataireMarchandise": {
            "id": 63,
            "nom": "BARRO'S",
            "email": "info@barros.com",
            "telephone": "+226 70 27 97 53",
            "nationalite": "Burkinabé",
            "createdBy": "Gloria Gloria",
            "createdAt": 1734371818366,
            "updateBy": null,
            "updateAt": 1734371818366
          },
          "pieceJustificatives": null,
          "codeSh": "234",
          "natureMarchandise": "BLE",
          "produitGrandeConsommation": true,
          "sensTrafic": "IMP",
          "modeTransport": "Route",
          "origineMarchandise": "CHINE",
          "blNumeroConnaissement": "0009238881",
          "portEmbarquement": "PAL",
          "nomNavire": "NAVI-TRANS",
          "nationaliteNavire": "CHINOISE",
          "nombreCamionsSouhaite": 6,
          "prixTransportSouhaiteTonne": 35000,
          "affichagePrixRecepisse": true,
          "paysProvenance": "CHINE",
          "poidsMarchandise": 3000,
          "villeProvenance": "HONG KONG",
          "paysDestination": "BURKINA FASO",
          "villeDestination": "Ouagadougou",
          "createdBy": "C464600",
          "statutPayement": null,
          "statutAffretement": true,
          "etatMarchandise": "TRANSIT",
          "datePayement": null,
          "createdAt": 1736860911573,
          "updateBy": null,
          "updateAt": 1736861304096
        },
        "affretementCamions": null,
        "createdBy": "chargeur Client",
        "createdAt": 1736861304007,
        "updateBy": null,
        "updateAt": 1736861304007
      },
      "parametrage": {
        "id": 15,
        "chargeur": {
          "id": 27,
          "nom": "Conseil des chargeurs CBC",
          "nationalite": "Burkinabé",
          "telephone": "91298899",
          "mail": "acbc@gmail.com",
          "repartitionFret": true,
          "compteClient": "C407000",
          "quotas": 0.6,
          "createdBy": "Conseil des chargeurs CBC",
          "createdAt": 1734373877310,
          "updateBy": null,
          "updateAt": 1734373877310
        },
        "nationalite": "Togolaise",
        "quota": 0.4,
        "type": "TRANSIT",
        "createdBy": "Conseil des chargeurs CBC",
        "updateBy": null,
        "createdAt": 1736776199274,
        "updateAt": 1736776199274
      },
      "poids": 300
    },
    {
      "id": 9,
      "camion": {
        "id": 86,
        "transporteur": {
          "id": 45,
          "raisonSociale": "Marco Transporteur",
          "telephone": "91131955",
          "adresse": null,
          "mail": "transporteur013@gmail.com",
          "nif": null,
          "rccm": null,
          "licenceTransport": null,
          "createdBy": "Marco Transporteur",
          "createdAt": 1736181596124,
          "updateBy": null,
          "updateAt": 1736181596124
        },
        "conducteur": {
          "id": 23,
          "nom": "Ouedraogo",
          "prenoms": "troaré",
          "numeroTelephone": "92 32 45 55",
          "numeroPermis": "550-20-45300",
          "dateEtablissementPermis": 950814060000,
          "lieuEtablissementPermis": "Ouagadougou",
          "associationAffiliation": "URT",
          "dateExpPermis": 1736441708000,
          "nationalite": "CNI-70-123-0030",
          "dateNaissance": "1980-01-17T19:00",
          "genre": "homme",
          "createdBy": "Conseil des chargeurs CBC",
          "createdAt": 1734375753622,
          "updateBy": null,
          "updateAt": 1734375753622
        },
        "immatriculation": "TG-8940",
        "chargeUtile": 1000,
        "capaciteAutorisee14": 1000,
        "nombreEssieu": 4,
        "dateExpVisiteTechnique": 1738281600000,
        "dateExpAssurance": 1738972800000,
        "pays": "TOGO",
        "nationalite": "Togolais",
        "marque": "MAN",
        "modeleCarteGrise": "Poids Lourd",
        "numeroCarteGrise": "098233112",
        "numeroCarteTransport": "CT-0993",
        "disponible": true,
        "piecesJustificatives": null,
        "etatCamion": "VALIDER",
        "motifRejete": null,
        "createdBy": "Marco Transporteur",
        "createdAt": 1736511894452,
        "updateBy": null,
        "updateAt": 1736513525358
      },
      "affretement": {
        "id": 96,
        "declarationFret": {
          "id": 104,
          "declarant": {
            "id": 21,
            "maisonTransit": "GLORIA",
            "telephone": "91298899",
            "mail": "aggloria@gmail.com",
            "compteClient": "C464600",
            "createdBy": "Gloria Gloria",
            "createdAt": 1734371818356,
            "updateBy": null,
            "updateAt": 1734371818356
          },
          "chargeur": {
            "id": 27,
            "nom": "Conseil des chargeurs CBC",
            "nationalite": "Burkinabé",
            "telephone": "91298899",
            "mail": "acbc@gmail.com",
            "repartitionFret": true,
            "compteClient": "C407000",
            "quotas": 0.6,
            "createdBy": "Conseil des chargeurs CBC",
            "createdAt": 1734373877310,
            "updateBy": null,
            "updateAt": 1734373877310
          },
          "destinataireMarchandise": {
            "id": 63,
            "nom": "BARRO'S",
            "email": "info@barros.com",
            "telephone": "+226 70 27 97 53",
            "nationalite": "Burkinabé",
            "createdBy": "Gloria Gloria",
            "createdAt": 1734371818366,
            "updateBy": null,
            "updateAt": 1734371818366
          },
          "pieceJustificatives": null,
          "codeSh": "234",
          "natureMarchandise": "BLE",
          "produitGrandeConsommation": true,
          "sensTrafic": "IMP",
          "modeTransport": "Route",
          "origineMarchandise": "CHINE",
          "blNumeroConnaissement": "0009238881",
          "portEmbarquement": "PAL",
          "nomNavire": "NAVI-TRANS",
          "nationaliteNavire": "CHINOISE",
          "nombreCamionsSouhaite": 6,
          "prixTransportSouhaiteTonne": 35000,
          "affichagePrixRecepisse": true,
          "paysProvenance": "CHINE",
          "poidsMarchandise": 3000,
          "villeProvenance": "HONG KONG",
          "paysDestination": "BURKINA FASO",
          "villeDestination": "Ouagadougou",
          "createdBy": "C464600",
          "statutPayement": null,
          "statutAffretement": true,
          "etatMarchandise": "TRANSIT",
          "datePayement": null,
          "createdAt": 1736860911573,
          "updateBy": null,
          "updateAt": 1736861304096
        },
        "affretementCamions": null,
        "createdBy": "chargeur Client",
        "createdAt": 1736861304007,
        "updateBy": null,
        "updateAt": 1736861304007
      },
      "parametrage": {
        "id": 15,
        "chargeur": {
          "id": 27,
          "nom": "Conseil des chargeurs CBC",
          "nationalite": "Burkinabé",
          "telephone": "91298899",
          "mail": "acbc@gmail.com",
          "repartitionFret": true,
          "compteClient": "C407000",
          "quotas": 0.6,
          "createdBy": "Conseil des chargeurs CBC",
          "createdAt": 1734373877310,
          "updateBy": null,
          "updateAt": 1734373877310
        },
        "nationalite": "Togolaise",
        "quota": 0.4,
        "type": "TRANSIT",
        "createdBy": "Conseil des chargeurs CBC",
        "updateBy": null,
        "createdAt": 1736776199274,
        "updateAt": 1736776199274
      },
      "poids": 900
    }
  ],
  "createdBy": "chargeur Client",
  "createdAt": 1736861304007,
  "updateBy": null,
  "updateAt": 1736861304007
}
