export enum RolesEnum {
  INSPECTEUR_PHYTOSANITAIRE = 'INSPECTEUR_PHYTOSANITAIRE',
  G_PHYTOSANITAIRE = 'PHYTOSANITAIRE', // Groupe phytosanitaire
  INSPECTEUR_VETERINAIRE = 'INSPECTEUR_VETERINAIRE',
  VETERINAIRE = 'VETERINAIRE',
  MANAGER = 'MANAGER',
  CONSULTANT = 'CONSULTANTS',
  VALIDATEUR = 'VALIDATEUR',
  COMPTABLE = 'COMPTABLE',
  INSPECTEUR = 'INSPECTEUR',
  SECRETAIRE = 'SECRETAIRE',
}
